### ISSUE TITLE
wmctrl -l not showing all windows

### ISSUE THREAD

**Issue by Lew-Rockwell-Fan** [dancor/wmctrl#5]
On the same machine under just plain Openbox, no DE per se, under  X, under Ubuntu 16.04 or 18.04 it works fine, but under Pclos, with the same setup, it misses a lot of windows. In both cases I'm using it in lxterminal running bash, in Openbox in X.

I found this:
https://bugzilla.redhat.com/show_bug.cgi?id=426383
but I haven't been able to figure out how to compile with a  flag.

Also this:
https://www.linuxquestions.org/questions/slackware-14/wmctrl-is-not-showing-all-windows-4175433231/
but ditto on compiling with a patch.

Any suggestions appreciated.

**Comment by zw963** [comment]
It maybe a issue related to Wayland.

from this link. https://bugs.launchpad.net/ubuntu/+source/gnome-terminal/+bug/1725991

wmctrl is for X window management whereas GNOME/GTK and some other apps are native Wayland not using X. Only legacy apps using Xwayland will show up in wmctrl. Although you could ask wmctrl for some kind of enhancement to list the non-X apps.

**Comment by Lew-Rockwell-Fan** [comment]
I doubt it's a Wayland issue. Wayland issues are very rare under X. Strangely when I got an email from this, it referred me to another thread I'd never posted in -  a thread pertaining to Wayland. Is github going crazy? But anyway, my issue was fixed by Tex, the pclos dev, who patched and compiled a version that works with Openbox under X in pclos.

**Comment by zw963** [comment]
I don't know why, several days ago, i can't see any konsole window in Wayland, but it works again since yesteray.\

```
 ╰─ $ 1  wmctrl -lx
0x01600007  0 konsole.konsole       lggram /home/zw963/Dropbox — Konsole
0x01a00003  0 Navigator.Nightly     lggram wmctrl -l not showing all windows · Issue #5 · dancor/wmctrl - Nightly
```

It really confusing.
